version: '3'

services:
  # proxy nginx
  nginx-proxy:
    image: nginx:1.23.1-alpine
    container_name: proxy_nginx
    ports:
      - "80:80"
    depends_on:
      - guest-library
      - admin-library
      - api-library
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf

  postgres-db:
    image: postgres:14.4-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=perpustakaan
    ports:
      - "8083:5432"

  guest-library:
    image: guest-library
    container_name: guest-library
    build:
      context: ./guest
    environment:
      PORT: "8081"
    restart: on-failure
  admin-library:
    image: admin-library
    container_name: admin-library
    build:
      context: ./admin
    environment:
      PORT: "3002"
    restart: on-failure
  api-library:
    image: api-library
    container_name: api-library
    build:
      context: ./api
    environment:
      PORT: "3000"
    restart: on-failure
