version: '3'

services:
  # proxy nginx
  nginx-proxy:
    image: nginx:1.23.1
    container_name: proxy_nginx
    ports:
      - "80:80"
    depends_on:
      - guest-perpustakaan
      - admin-perpustakaan
      - api-perpustakaan
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf

  # guest perpustakaan
  guest-perpustakaan:
    image: guest-perpustakaan
    container_name: guest-perpustakaan
    build:
      context: ./guest
    environment:
      PORT: "8081"
    restart: on-failure
  admin-perpustakaan:
    image: admin-perpustakaan
    container_name: admin-perpustakaan
    build:
      context: ./admin
    environment:
      PORT: "3002"
    restart: on-failure
  api-perpustakaan:
    image: api-perpustakaan
    container_name: api-perpustakaan
    build:
      context: ./api
    environment:
      PORT: "3000"
    restart: on-failure